version: '3'

services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - '.:/projects'
      - '/projects/node_modules'
    tty: true
    environment:
      HUBOT_SLACK_TOKEN: ${HUBOT_SLACK_TOKEN}
    command: /bin/sh
